(cleanup): check-upgrade CI

diff --git a/.github/workflows/check-upgrade.yml b/.github/workflows/check-upgrade.yml
--- a/.github/workflows/check-upgrade.yml
+++ b/.github/workflows/check-upgrade.yml
@@ -1,10 +1,8 @@
 name: Check BurpSuite latest version if a new one is out trigger update CI job
 
 on:
-  push:
-    branches: ["main"]
   schedule:
-    - cron: "0 5 * * *"   # Every day at 05:00 A.M. UTC run check
+    - cron: "0 23 * * *"   # Every day at 23h00 UTC run check
 jobs:
   Check-BurpSuite-NewVersion:
     runs-on: ubuntu-latest
@@ -38,65 +36,5 @@ jobs:
       - name: Build latest update from upstream
         run: |
           pkgver_new=$(curl https://portswigger.net/burp/releases | grep community | sed -nE "s/.*professional-community-(.*)\" class=\".*/\1/p" | head -n  1 | tr -d '\n' | tr '-' '.') echo $pkgver_new > tmp-latest-version
-          diff aur-burpsuite/latest_version tmp-latest-version 2>/dev/null || echo "Not the same"  # if not the same trigger update CI
-          exit 0
-      - name: Copy updated scripts to AUR repo and commit
-        run: |
-          cd burpsuite
-          git config --global --add safe.directory /__w/aur-burpsuite/aur-burpsuite
-      - uses: EndBug/add-and-commit@v9
-        with:
-         # The arguments for the `git add` command (see the paragraph below for more info)
-         # Default: '.'
-         add: 'latest_version'
-
-         # The name of the user that will be displayed as the author of the commit.
-         # Default: depends on the default_author input
-         author_name: "GITHUB CI"
-
-         # The email of the user that will be displayed as the author of the commit.
-         # Default: depends on the default_author input
-         author_email: "14914796+AkechiShiro@users.noreply.github.com"
-
-         # Additional arguments for the git commit command. The --message argument is already set by the message input.
-         # Default: ''
-         commit: --signoff
-
-         # The name of the custom committer you want to use, if different from the author of the commit.
-         # Default: the name of the author (set with either author_name or default_author)
-         committer_name: "Samy Lahfa"
-
-         # The email of the custom committer you want to use, if different from the author of the commit.
-         # Default: the email of the author (set with either author_email or default_author)
-         committer_email: "14914796+AkechiShiro@users.noreply.github.com"
-
-         # The local path to the directory where your repository is located. You should use actions/checkout first to set it up.
-         # Default: '.'
-         cwd: '.'
-
-         # Determines the way the action fills missing author name and email. Three options are available:
-         # - github_actor -> UserName <UserName@users.noreply.github.com>
-         # - user_info -> Your Display Name <your-actual@email.com>
-         # - github_actions -> github-actions <email associated with the github logo>
-         # Default: github_actor
-         default_author: github_actor
-
-         # Arguments for the git fetch command. If set to false, the action won't fetch the repo.
-         # For more info as to why fetching is usually recommended, please see the "Performance on large repos" FAQ. 
-         # Default: --tags --force
-         fetch: false
-
-         # The message for the commit.
-         # Default: 'Commit from GitHub Actions (name of the workflow)'
-         #message: ''
-
-         # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
-         # - ignore -> errors will be logged but the step won't fail
-         # - exitImmediately -> the action will stop right away, and the step will fail
-         # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
-         # Default: ignore
-         pathspec_error_handling: ignore
-
-         # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
-         # Default: true
-         push: true
+          (diff aur-burpsuite/latest_version tmp-latest-version 2>/dev/null || exit 0) && exit 1  
+          # if not the same trigger update CI (on-success) else on-failure do nothing
